import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react'; // Import useState
import { User, Mail, Phone, BookOpenCheck } from 'lucide-react';
import './Registration.css'; // Make sure to create this new CSS file
import registerImage from './assets/register.jpg'; // Import the new image
function Registration() {
    const [isSubmitted, setIsSubmitted] = useState(false);
    const handleSubmit = (e) => {
        e.preventDefault(); // Prevents the page from reloading on submit
        setIsSubmitted(true); // Show the pop-up
        // Here you would typically send form data to a server
    };
    return (_jsxs("div", { className: "reg-page-container", children: [isSubmitted && (_jsxs("div", { className: "popup-message", children: [_jsx("span", { children: "You successfully registered yourself!" }), _jsx("button", { onClick: () => setIsSubmitted(false), className: "popup-close-btn", children: "\u00D7" })] })), _jsxs("div", { className: "reg-form-wrapper", children: [_jsxs("div", { className: "reg-form-left", children: [_jsx("h1", { children: "Fill your details" }), _jsx("p", { className: "subtitle", children: "And get one month of Trial!" }), _jsxs("form", { className: "reg-form", onSubmit: handleSubmit, children: [_jsxs("div", { className: "reg-input-group", children: [_jsx("label", { htmlFor: "firstName", children: "First Name*" }), _jsxs("div", { className: "reg-input-wrapper", children: [_jsx(User, { className: "reg-input-icon", size: 18 }), _jsx("input", { type: "text", id: "firstName", placeholder: "Enter your first name", name: "firstName", required: true })] })] }), _jsxs("div", { className: "reg-input-group", children: [_jsx("label", { htmlFor: "lastName", children: "Last Name*" }), _jsxs("div", { className: "reg-input-wrapper", children: [_jsx(User, { className: "reg-input-icon", size: 18 }), _jsx("input", { type: "text", id: "lastName", placeholder: "Enter your last name", name: "lastName", required: true })] })] }), _jsxs("div", { className: "reg-input-group", children: [_jsx("label", { htmlFor: "email", children: "Email*" }), _jsxs("div", { className: "reg-input-wrapper", children: [_jsx(Mail, { className: "reg-input-icon", size: 18 }), _jsx("input", { type: "email", id: "email", placeholder: "Enter your email", name: "email", required: true })] })] }), _jsxs("div", { className: "reg-input-group", children: [_jsx("label", { htmlFor: "phone", children: "Phone Number*" }), _jsxs("div", { className: "reg-input-wrapper", children: [_jsx(Phone, { className: "reg-input-icon", size: 18 }), _jsx("input", { type: "tel", id: "phone", placeholder: "Enter your phone no.", name: "phone", required: true })] })] }), _jsxs("div", { className: "reg-input-group", children: [_jsx("label", { htmlFor: "course", children: "Choose your Course*" }), _jsxs("div", { className: "reg-input-wrapper", children: [_jsx(BookOpenCheck, { className: "reg-input-icon", size: 18 }), _jsx("input", { type: "text", id: "course", placeholder: "Choose your Course", name: "course", required: true })] })] }), _jsxs("div", { className: "reg-checkbox-group", children: [_jsx("input", { type: "checkbox", id: "agree", name: "agree", required: true }), _jsx("label", { htmlFor: "agree", children: "I agree to the processing of personal data*" })] }), _jsx("button", { type: "submit", className: "reg-submit-btn", children: "SUBMIT" })] })] }), _jsx("div", { className: "reg-form-right", children: _jsx("img", { src: registerImage, alt: "Person studying with a tablet", className: "illustration-image" }) })] })] }));
}
export default Registration;
